# Generated by Django 3.2.4 on 2021-08-31 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=24)),
                ('last_name', models.CharField(blank=True, max_length=24)),
                ('age', models.IntegerField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customusermodel')),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
